# Generated by Django 4.2 on 2023-05-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_start', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fan_stop', models.DecimalField(decimal_places=1, max_digits=3)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
            ],
        ),
    ]
