# Generated by Django 4.2 on 2023-07-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='temp',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
