# Generated by Django 4.2 on 2023-08-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_schedule_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DecimalField(decimal_places=1, max_digits=3)),
                ('humid', models.DecimalField(decimal_places=1, max_digits=3)),
                ('moist', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='temp',
        ),
    ]
